import AppCore
@testable import FeatureArchiveBrowser
import NikoMusicCore
import XCTest

@MainActor
final class ArchiveUserFlowTests: XCTestCase {
    func testFixtureUserFlowScanSearchOpenDryRunLeavesArchiveUnchanged() async throws {
        try CubaseFixtures.ensureGenerated()
        setenv("NIKO_MUSIC_HUB_FIXTURE_ROOT", CubaseFixtures.archiveRoot.path, 1)
        setenv("NIKO_MUSIC_HUB_DRY_RUN_OPEN", "1", 1)
        defer {
            unsetenv("NIKO_MUSIC_HUB_FIXTURE_ROOT")
            unsetenv("NIKO_MUSIC_HUB_DRY_RUN_OPEN")
        }

        let result = try ArchiveUserFlowSmoke.run(
            fixtureRoot: CubaseFixtures.archiveRoot,
            context: TestToolContext.make()
        )

        XCTAssertEqual(result.userFlow, "scan_search_open")
        XCTAssertGreaterThanOrEqual(result.songCount, 4)
        XCTAssertEqual(result.searchQuery, "neon hk")
        XCTAssertEqual(result.searchMatchCount, 1)
        XCTAssertEqual(result.selectedTitle, "Neon Hook")
        XCTAssertGreaterThanOrEqual(result.diagnosticsSongCount, 4)
        XCTAssertGreaterThanOrEqual(result.diagnosticsSkippedCount, 1)
        XCTAssertTrue(result.writeProbeDenied)
        XCTAssertTrue(result.archiveTreeUnchanged)
        XCTAssertTrue(result.dryRunCPRPath.contains("Neon Hook"))
        XCTAssertTrue(result.dryRunCPRPath.hasSuffix("Neon Hook.cpr"))
        XCTAssertEqual(result.dryRunCPRDisplayPath, Song.displayDryRunPath(result.dryRunCPRPath))
        XCTAssertTrue(result.dryRunLogLine?.contains("[dry-run] open CPR:") == true)
        if let dryRunLogLine = result.dryRunLogLine {
            XCTAssertEqual(
                result.dryRunLogDisplayLine,
                DiagnosticsPathRedactor.redactPathsInText(dryRunLogLine)
            )
        }
        XCTAssertTrue(result.searchMatchSummary.contains("neon"))
        XCTAssertTrue(result.searchMatchSummary.contains("hk"))
        XCTAssertFalse(result.searchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.searchDiagnosticsExportContainsMatch)
        XCTAssertTrue(result.searchDiagnosticsExportContainsSummaryLine)
        XCTAssertTrue(result.diagnosticsExportSummaryLine.contains("summary_line=roots:"))
        XCTAssertTrue(result.diagnosticsExportSummaryLine.contains("Scanned 7 songs"))
        XCTAssertTrue(result.diagnosticsExportSummaryLine.contains("1 song(s) with 1 warning(s)"))
        XCTAssertTrue(result.diagnosticsExportSummaryLine.contains("Broken Folder Example"))
        XCTAssertTrue(result.diagnosticsExportSummaryLine.contains("2 skipped at roots"))
        XCTAssertTrue(result.diagnosticsPanelMatchesExportSummary)
        XCTAssertEqual(result.fixtureScanHealthBadge, "1 song warning · 2 skipped at roots")
        XCTAssertTrue(result.fixtureScanHealthBadgeMatchesExport)
        XCTAssertFalse(result.invalidRootDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.invalidRootExportContainsRootHealthBadge)
        XCTAssertTrue(result.invalidRootPanelRootHealthBadge.contains("invalid root"))
        XCTAssertTrue(result.invalidRootPanelRootHealthBadge.contains("root warning"))
        XCTAssertTrue(result.invalidRootPanelBadgeMatchesExport)
        XCTAssertEqual(
            ArchiveDiagnosticsPanelAccessibility.rootHealthBadge,
            "archive_diagnostics_root_health_badge"
        )
        XCTAssertTrue(result.diagnosticsPanelSupportSummary.hasPrefix("roots:"))
        XCTAssertTrue(result.diagnosticsPanelSupportSummary.contains("Scanned 7 songs"))
        XCTAssertTrue(result.rankingLabMainPreviewSummary.contains("Lab Song v3 mix.wav"))
        XCTAssertTrue(result.rankingLabMainPreviewSummary.contains("v3"))
        XCTAssertTrue(result.rankingLabMainPreviewSummary.contains("wav"))
        XCTAssertFalse(result.rankingLabDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.rankingLabDiagnosticsExportContainsMatch)
        XCTAssertFalse(result.tiebreakLabDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.tiebreakLabDiagnosticsExportContainsTiebreak)
        XCTAssertFalse(result.tiebreakPanelPreviewRankingHeader.isEmpty)
        XCTAssertTrue(result.tiebreakPanelPreviewRankingHeaderMatchesExport)
        XCTAssertTrue(result.tiebreakPanelPreviewTiebreakCallout.contains("Equal score — longer preview"))
        XCTAssertTrue(result.tiebreakPanelPreviewTiebreakCalloutMatchesExport)
        XCTAssertFalse(result.versionTiebreakLabDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.versionTiebreakLabDiagnosticsExportContainsTiebreak)
        XCTAssertTrue(result.versionTiebreakPanelCallout.contains("Equal score — version v3 beat v2"))
        XCTAssertTrue(result.versionTiebreakPanelCalloutMatchesExport)
        XCTAssertFalse(result.extensionTiebreakLabDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.extensionTiebreakLabDiagnosticsExportContainsTiebreak)
        XCTAssertTrue(result.extensionTiebreakPanelCallout.contains("Equal score — preferred flac over mp3"))
        XCTAssertTrue(result.extensionTiebreakPanelCalloutMatchesExport)
        XCTAssertTrue(
            result.brokenFolderDisplayWarnings.contains(where: { $0.localizedCaseInsensitiveContains("CPR") })
        )
        XCTAssertEqual(result.brokenFolderSidecarNotes, "notes only")
        XCTAssertEqual(result.warningSearchQuery, "project")
        XCTAssertEqual(result.warningSearchMatchCount, 1)
        XCTAssertEqual(result.warningSearchMatchTitle, "Broken Folder Example")
        XCTAssertTrue(result.warningSearchMatchSummary.contains("scan warning"))
        XCTAssertTrue(result.warningSearchMatchSummary.contains("project"))
        XCTAssertFalse(result.warningSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.warningSearchDiagnosticsExportContainsMatch)
        XCTAssertEqual(result.fuzzyWarningSearchQuery, "ncpr fnd")
        XCTAssertEqual(result.fuzzyWarningSearchMatchCount, 1)
        XCTAssertEqual(result.fuzzyWarningSearchMatchTitle, "Broken Folder Example")
        XCTAssertTrue(result.fuzzyWarningSearchMatchSummary.contains("fuzzy scan warning"))
        XCTAssertTrue(result.fuzzyWarningSearchMatchSummary.contains("ncpr"))
        XCTAssertTrue(result.fuzzyWarningSearchMatchSummary.contains("fnd"))
        XCTAssertFalse(result.fuzzyWarningSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.fuzzyWarningSearchDiagnosticsExportContainsMatch)
        XCTAssertEqual(result.notesSearchQuery, "nts nly")
        XCTAssertEqual(result.notesSearchMatchCount, 1)
        XCTAssertEqual(result.notesSearchMatchTitle, "Broken Folder Example")
        XCTAssertTrue(result.notesSearchMatchSummary.contains("fuzzy song note"))
        XCTAssertTrue(result.notesSearchMatchSummary.contains("nts"))
        XCTAssertTrue(result.notesSearchMatchSummary.contains("nly"))
        XCTAssertFalse(result.notesSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.notesSearchDiagnosticsExportContainsMatch)
        XCTAssertEqual(result.folderSearchQuery, "brkn fld")
        XCTAssertEqual(result.folderSearchMatchCount, 1)
        XCTAssertEqual(result.folderSearchMatchTitle, "Broken Folder Example")
        XCTAssertTrue(result.folderSearchMatchSummary.contains("fuzzy folder"))
        XCTAssertTrue(result.folderSearchMatchSummary.contains("brkn"))
        XCTAssertTrue(result.folderSearchMatchSummary.contains("fld"))
        XCTAssertFalse(result.folderSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.folderSearchDiagnosticsExportContainsMatch)
        XCTAssertEqual(result.cprSearchQuery, "neohkv2")
        XCTAssertEqual(result.cprSearchMatchCount, 1)
        XCTAssertEqual(result.cprSearchMatchTitle, "Neon Hook")
        XCTAssertTrue(result.cprSearchMatchSummary.contains("fuzzy CPR file"))
        XCTAssertTrue(result.cprSearchMatchSummary.contains("neohkv2"))
        XCTAssertFalse(result.cprSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.cprSearchDiagnosticsExportContainsMatch)
        XCTAssertEqual(result.previewSearchQuery, "ranking lab v3 mx")
        XCTAssertGreaterThanOrEqual(result.previewSearchMatchCount, 1)
        XCTAssertEqual(result.previewSearchMatchTitle, "Preview Ranking Lab")
        XCTAssertTrue(result.previewSearchMatchSummary.contains("fuzzy preview file"))
        XCTAssertTrue(result.previewSearchMatchSummary.contains("v3"))
        XCTAssertTrue(result.previewSearchMatchSummary.contains("mx") || result.previewSearchMatchSummary.contains("fuzzy preview file"))
        XCTAssertFalse(result.previewSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.previewSearchDiagnosticsExportContainsMatch)
        XCTAssertEqual(result.skippedSearchQuery, "LOOSE_FILE.txt")
        XCTAssertGreaterThanOrEqual(result.skippedSearchMatchCount, 1)
        XCTAssertEqual(result.skippedSearchMatchLabel, "LOOSE_FILE.txt")
        XCTAssertTrue(result.skippedSearchMatchSummary.contains("skipped label"))
        XCTAssertFalse(result.skippedSearchDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.skippedSearchDiagnosticsExportContainsMatch)
        XCTAssertFalse(result.summaryTruncationDiagnosticsExportPath.isEmpty)
        XCTAssertTrue(result.summaryTruncationDiagnosticsExportContainsTruncation)
        XCTAssertEqual(
            result.summaryTruncationPanelFootnote,
            "Support summary shows 5 warning song titles; 3 more listed below."
        )
        XCTAssertTrue(result.summaryTruncationPanelFootnoteMatchesDiagnostics)
    }
}
