#!/usr/bin/env bash
# Generates deterministic Cubase archive fixtures for unit tests and E2E.
# CPR files are zero-byte placeholders (not copied from real projects).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
FIXTURE_ROOT="$ROOT/Fixtures/CubaseArchive"

write_minimal_wav() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  /usr/bin/python3 - "$path" <<'PY'
import struct, sys, wave
path = sys.argv[1]
with wave.open(path, "w") as w:
    w.setnchannels(1)
    w.setsampwidth(2)
    w.setframerate(44100)
    w.writeframes(b"\x00\x00" * 4410)  # ~0.1s silence
PY
}

write_placeholder_cpr() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  : >"$path"
}

rm -rf "$FIXTURE_ROOT"
mkdir -p "$FIXTURE_ROOT"

# Neon Hook — full mix in Mixdown beats stem names
write_placeholder_cpr "$FIXTURE_ROOT/Neon Hook/Neon Hook v2.cpr"
write_placeholder_cpr "$FIXTURE_ROOT/Neon Hook/Neon Hook.cpr"
# Latest CPR for E2E is Neon Hook.cpr (newer mtime than v2)
/usr/bin/python3 - "$FIXTURE_ROOT/Neon Hook/Neon Hook.cpr" <<'PY'
import os, sys, time
path = sys.argv[1]
now = time.time() + 120
os.utime(path, (now, now))
PY
write_minimal_wav "$FIXTURE_ROOT/Neon Hook/Mixdown/Neon Hook v3.wav"
write_minimal_wav "$FIXTURE_ROOT/Neon Hook/Mixdown/Neon Hook instr.wav"
mkdir -p "$FIXTURE_ROOT/Neon Hook/Ideas"
touch "$FIXTURE_ROOT/Neon Hook/Ideas/Neon Hook topline.mid"

# Second Song — instr vs full mix filename competition
write_placeholder_cpr "$FIXTURE_ROOT/Second Song/Second Song.cpr"
write_minimal_wav "$FIXTURE_ROOT/Second Song/Mixdown/Second Song mixdown.wav"
write_minimal_wav "$FIXTURE_ROOT/Second Song/Mixdown/Second Song instr.wav"

# Broken folder — no CPR
mkdir -p "$FIXTURE_ROOT/Broken Folder Example"
echo "notes only" >"$FIXTURE_ROOT/Broken Folder Example/notes.txt"

cat >"$FIXTURE_ROOT/README.md" <<'EOF'
# Cubase archive fixtures

Generated by `script/fixtures/generate_cubase_archive_fixtures.sh`.

- `.cpr` files are **empty placeholders** (not real Cubase projects).
- `.wav` files are minimal valid mono WAV (~0.1s silence).
- Do not copy real MacBook archive binaries into this tree.
EOF

echo "Generated fixtures under $FIXTURE_ROOT"
