import Foundation

public enum ArchiveUserFlowSmokeError: Error, Equatable, Sendable {
    case neonHookNotFound
    case rankingLabNotFound
    case missingDryRunPath
    case missingRankingLabPreviewSummary
    case rankingLabDiagnosticsExportMissingMatch
    case rankingLabPanelPreviewRankingMismatch
    case previewTiebreakLabNotFound(String)
    case previewTiebreakLabExportMissing(String)
    case previewTiebreakLabPanelMismatch(String)
    case brokenFolderNotFound
    case brokenFolderMissingDisplayWarnings
    case brokenFolderMissingSidecarNotes
    case brokenFolderSelectedSongDiagnosticsExportMissingSection
    case brokenFolderSelectedSongPanelMismatch
    case songSearchNoMatch(String)
    case songSearchMissingExplainability(String)
    case songSearchExportMissingMatch(String)
    case skippedSearchNoMatch
    case skippedSearchMissingExplainability
    case searchDiagnosticsExportMissingMatch
    case searchDiagnosticsExportMissingSummaryLine
    case activeSearchPanelMismatch
    case diagnosticsExportFailed
    case diagnosticsPanelSupportSummaryMismatch
    case fixtureScanHealthBadgeMissing
    case fixtureScanHealthBadgeMismatch
    case fixtureScanSkippedPanelMismatch
    case fixtureScanSongWarningsPanelMismatch
    case fixtureScanCountsPanelMismatch
    case invalidRootDiagnosticsExportFailed
    case invalidRootExportMissingRootHealthBadge
    case invalidRootPanelRootHealthBadgeMissing
    case invalidRootPanelGlobalWarningsMismatch
    case summaryTruncationRootMissing
    case summaryTruncationDiagnosticsExportMissingTruncation
    case summaryTruncationPanelFootnoteMissing
    case summaryTruncationPanelFootnoteMismatch
    case skippedSearchDiagnosticsExportMissingMatch
    case skippedSearchPanelActiveSkippedSearchMismatch
}
