import Foundation

/// Flat accessors for tests and legacy call sites; prefer nested sections on ``ArchiveUserFlowSmokeResult``.
extension ArchiveUserFlowSmokeResult {
    public var userFlow: String { core.userFlow }
    public var songCount: Int { core.songCount }
    public var searchQuery: String { primarySearch.query }
    public var searchMatchCount: Int { primarySearch.matchCount }
    public var selectedTitle: String { core.selectedTitle }
    public var dryRunCPRPath: String { core.dryRunCPRPath }
    public var dryRunCPRDisplayPath: String { core.dryRunCPRDisplayPath }
    public var dryRunLogLine: String? { core.dryRunLogLine }
    public var dryRunLogDisplayLine: String? { core.dryRunLogDisplayLine }
    public var writeProbeDenied: Bool { core.writeProbeDenied }
    public var archiveTreeUnchanged: Bool { core.archiveTreeUnchanged }
    public var diagnosticsSongCount: Int { fixtureDiagnostics.songCount }
    public var diagnosticsSkippedCount: Int { fixtureDiagnostics.skippedCount }
    public var searchMatchSummary: String { core.searchMatchSummary }
    public var rankingLabMainPreviewSummary: String { rankingLab.mainPreviewSummary }
    public var rankingLabDiagnosticsExportPath: String { rankingLab.exportPath }
    public var rankingLabDiagnosticsExportContainsMatch: Bool { rankingLab.exportContainsMatch }
    public var rankingLabPanelScanCallout: String { rankingLab.panelScanCallout }
    public var rankingLabPanelScanCalloutMatchesExport: Bool { rankingLab.panelScanCalloutMatchesExport }
    public var rankingLabPanelSelectedHeader: String { rankingLab.panelSelectedHeader }
    public var rankingLabPanelSelectedHeaderMatchesExport: Bool { rankingLab.panelSelectedHeaderMatchesExport }
    public var rankingLabPanelTooShortBreakdownLine: String { rankingLab.panelTooShortBreakdownLine }
    public var rankingLabPanelTooShortBreakdownMatchesExport: Bool { rankingLab.panelTooShortBreakdownMatchesExport }
    public var rankingLabPanelTiebreakLegend: String { rankingLab.panelTiebreakLegend }
    public var rankingLabPanelTiebreakLegendMatchesExport: Bool { rankingLab.panelTiebreakLegendMatchesExport }
    public var rankingLabPanelMainPreviewSummary: String { rankingLab.panelMainPreviewSummary }
    public var rankingLabPanelMainPreviewSummaryMatchesExport: Bool { rankingLab.panelMainPreviewSummaryMatchesExport }
    public var rankingLabPanelRankedPreviewLines: String { rankingLab.panelRankedPreviewLines }
    public var rankingLabPanelRankedPreviewLinesMatchExport: Bool { rankingLab.panelRankedPreviewLinesMatchExport }
    public var tiebreakLabDiagnosticsExportPath: String { tiebreakLabs.duration.exportPath }
    public var tiebreakLabDiagnosticsExportContainsTiebreak: Bool { tiebreakLabs.duration.exportContainsTiebreak }
    public var tiebreakPanelPreviewRankingHeader: String { tiebreakLabs.duration.panelHeader }
    public var tiebreakPanelPreviewRankingHeaderMatchesExport: Bool { tiebreakLabs.duration.panelHeaderMatchesExport }
    public var tiebreakPanelPreviewTiebreakCallout: String { tiebreakLabs.duration.panelCallout }
    public var tiebreakPanelPreviewTiebreakCalloutMatchesExport: Bool { tiebreakLabs.duration.panelCalloutMatchesExport }
    public var versionTiebreakLabDiagnosticsExportPath: String { tiebreakLabs.version.exportPath }
    public var versionTiebreakLabDiagnosticsExportContainsTiebreak: Bool { tiebreakLabs.version.exportContainsTiebreak }
    public var versionTiebreakPanelCallout: String { tiebreakLabs.version.panelCallout }
    public var versionTiebreakPanelCalloutMatchesExport: Bool { tiebreakLabs.version.panelCalloutMatchesExport }
    public var extensionTiebreakLabDiagnosticsExportPath: String { tiebreakLabs.extensionLab.exportPath }
    public var extensionTiebreakLabDiagnosticsExportContainsTiebreak: Bool { tiebreakLabs.extensionLab.exportContainsTiebreak }
    public var extensionTiebreakPanelCallout: String { tiebreakLabs.extensionLab.panelCallout }
    public var extensionTiebreakPanelCalloutMatchesExport: Bool { tiebreakLabs.extensionLab.panelCalloutMatchesExport }
    public var brokenFolderDisplayWarnings: [String] { brokenFolder.displayWarnings }
    public var brokenFolderSidecarNotes: String? { brokenFolder.sidecarNotes }
    public var brokenFolderSelectedSongDiagnosticsExportPath: String { brokenFolder.selectedSongExportPath }
    public var brokenFolderSelectedSongPanelTitleLine: String { brokenFolder.panelTitleLine }
    public var brokenFolderSelectedSongPanelTitleLineMatchesExport: Bool { brokenFolder.panelTitleLineMatchesExport }
    public var brokenFolderSelectedSongPanelCprLine: String { brokenFolder.panelCprLine }
    public var brokenFolderSelectedSongPanelCprLineMatchesExport: Bool { brokenFolder.panelCprLineMatchesExport }
    public var brokenFolderSelectedSongPanelWarningLines: String { brokenFolder.panelWarningLines }
    public var brokenFolderSelectedSongPanelWarningLinesMatchExport: Bool { brokenFolder.panelWarningLinesMatchExport }
    public var brokenFolderSelectedSongPanelNotesLine: String { brokenFolder.panelNotesLine }
    public var brokenFolderSelectedSongPanelNotesLineMatchesExport: Bool { brokenFolder.panelNotesLineMatchesExport }
    public var warningSearchQuery: String { searches.warning.query }
    public var warningSearchMatchCount: Int { searches.warning.matchCount }
    public var warningSearchMatchTitle: String { searches.warning.matchTitle }
    public var warningSearchMatchSummary: String { searches.warning.matchSummary }
    public var warningSearchDiagnosticsExportPath: String { searches.warning.exportPath }
    public var warningSearchDiagnosticsExportContainsMatch: Bool { searches.warning.exportContainsMatch }
    public var warningSearchPanelQueryLine: String { searches.warning.panel.queryLine }
    public var warningSearchPanelQueryLineMatchesExport: Bool { searches.warning.panel.queryLineMatchesExport }
    public var warningSearchPanelMatchLines: String { searches.warning.panel.matchLinesJoined }
    public var warningSearchPanelMatchLinesMatchExport: Bool { searches.warning.panel.matchLinesMatchExport }
    public var fuzzyWarningSearchQuery: String { searches.fuzzyWarning.query }
    public var fuzzyWarningSearchMatchCount: Int { searches.fuzzyWarning.matchCount }
    public var fuzzyWarningSearchMatchTitle: String { searches.fuzzyWarning.matchTitle }
    public var fuzzyWarningSearchMatchSummary: String { searches.fuzzyWarning.matchSummary }
    public var fuzzyWarningSearchDiagnosticsExportPath: String { searches.fuzzyWarning.exportPath }
    public var fuzzyWarningSearchDiagnosticsExportContainsMatch: Bool { searches.fuzzyWarning.exportContainsMatch }
    public var fuzzyWarningSearchPanelQueryLine: String { searches.fuzzyWarning.panel.queryLine }
    public var fuzzyWarningSearchPanelQueryLineMatchesExport: Bool { searches.fuzzyWarning.panel.queryLineMatchesExport }
    public var fuzzyWarningSearchPanelMatchLines: String { searches.fuzzyWarning.panel.matchLinesJoined }
    public var fuzzyWarningSearchPanelMatchLinesMatchExport: Bool { searches.fuzzyWarning.panel.matchLinesMatchExport }
    public var notesSearchQuery: String { searches.notes.query }
    public var notesSearchMatchCount: Int { searches.notes.matchCount }
    public var notesSearchMatchTitle: String { searches.notes.matchTitle }
    public var notesSearchMatchSummary: String { searches.notes.matchSummary }
    public var notesSearchDiagnosticsExportPath: String { searches.notes.exportPath }
    public var notesSearchDiagnosticsExportContainsMatch: Bool { searches.notes.exportContainsMatch }
    public var notesSearchPanelQueryLine: String { searches.notes.panel.queryLine }
    public var notesSearchPanelQueryLineMatchesExport: Bool { searches.notes.panel.queryLineMatchesExport }
    public var notesSearchPanelMatchLines: String { searches.notes.panel.matchLinesJoined }
    public var notesSearchPanelMatchLinesMatchExport: Bool { searches.notes.panel.matchLinesMatchExport }
    public var folderSearchQuery: String { searches.folder.query }
    public var folderSearchMatchCount: Int { searches.folder.matchCount }
    public var folderSearchMatchTitle: String { searches.folder.matchTitle }
    public var folderSearchMatchSummary: String { searches.folder.matchSummary }
    public var folderSearchDiagnosticsExportPath: String { searches.folder.exportPath }
    public var folderSearchDiagnosticsExportContainsMatch: Bool { searches.folder.exportContainsMatch }
    public var folderSearchPanelQueryLine: String { searches.folder.panel.queryLine }
    public var folderSearchPanelQueryLineMatchesExport: Bool { searches.folder.panel.queryLineMatchesExport }
    public var folderSearchPanelMatchLines: String { searches.folder.panel.matchLinesJoined }
    public var folderSearchPanelMatchLinesMatchExport: Bool { searches.folder.panel.matchLinesMatchExport }
    public var cprSearchQuery: String { searches.cpr.query }
    public var cprSearchMatchCount: Int { searches.cpr.matchCount }
    public var cprSearchMatchTitle: String { searches.cpr.matchTitle }
    public var cprSearchMatchSummary: String { searches.cpr.matchSummary }
    public var cprSearchDiagnosticsExportPath: String { searches.cpr.exportPath }
    public var cprSearchDiagnosticsExportContainsMatch: Bool { searches.cpr.exportContainsMatch }
    public var cprSearchPanelQueryLine: String { searches.cpr.panel.queryLine }
    public var cprSearchPanelQueryLineMatchesExport: Bool { searches.cpr.panel.queryLineMatchesExport }
    public var cprSearchPanelMatchLines: String { searches.cpr.panel.matchLinesJoined }
    public var cprSearchPanelMatchLinesMatchExport: Bool { searches.cpr.panel.matchLinesMatchExport }
    public var previewSearchQuery: String { searches.preview.query }
    public var previewSearchMatchCount: Int { searches.preview.matchCount }
    public var previewSearchMatchTitle: String { searches.preview.matchTitle }
    public var previewSearchMatchSummary: String { searches.preview.matchSummary }
    public var previewSearchDiagnosticsExportPath: String { searches.preview.exportPath }
    public var previewSearchDiagnosticsExportContainsMatch: Bool { searches.preview.exportContainsMatch }
    public var previewSearchPanelQueryLine: String { searches.preview.panel.queryLine }
    public var previewSearchPanelQueryLineMatchesExport: Bool { searches.preview.panel.queryLineMatchesExport }
    public var previewSearchPanelMatchLines: String { searches.preview.panel.matchLinesJoined }
    public var previewSearchPanelMatchLinesMatchExport: Bool { searches.preview.panel.matchLinesMatchExport }
    public var skippedSearchQuery: String { skippedSearch.query }
    public var skippedSearchMatchCount: Int { skippedSearch.matchCount }
    public var skippedSearchMatchLabel: String { skippedSearch.matchLabel }
    public var skippedSearchMatchSummary: String { skippedSearch.matchSummary }
    public var searchDiagnosticsExportPath: String { primarySearch.exportPath }
    public var searchDiagnosticsExportContainsMatch: Bool { primarySearch.exportContainsMatch }
    public var searchDiagnosticsExportContainsSummaryLine: Bool { primarySearch.exportContainsSummaryLine }
    public var searchPanelQueryLine: String { primarySearch.panel.queryLine }
    public var searchPanelQueryLineMatchesExport: Bool { primarySearch.panel.queryLineMatchesExport }
    public var searchPanelMatchLines: String { primarySearch.panel.matchLinesJoined }
    public var searchPanelMatchLinesMatchExport: Bool { primarySearch.panel.matchLinesMatchExport }
    public var diagnosticsExportSummaryLine: String { primarySearch.exportSummaryLine }
    public var diagnosticsPanelSupportSummary: String { fixtureDiagnostics.panelSupportSummary }
    public var diagnosticsPanelMatchesExportSummary: Bool { fixtureDiagnostics.panelMatchesExportSummary }
    public var fixtureScanHealthBadge: String { fixtureDiagnostics.healthBadge }
    public var fixtureScanHealthBadgeMatchesExport: Bool { fixtureDiagnostics.healthBadgeMatchesExport }
    public var fixtureScanSkippedPanelLines: String { fixtureDiagnostics.skippedPanelLines }
    public var fixtureScanSkippedPanelLinesMatchExport: Bool { fixtureDiagnostics.skippedPanelLinesMatchExport }
    public var fixtureScanSongWarningsPanelLines: String { fixtureDiagnostics.songWarningsPanelLines }
    public var fixtureScanSongWarningsPanelLinesMatchExport: Bool { fixtureDiagnostics.songWarningsPanelLinesMatchExport }
    public var fixtureScanCountsPanelSongsValue: String { fixtureDiagnostics.countsPanelSongsValue }
    public var fixtureScanCountsPanelSongWarningsValue: String { fixtureDiagnostics.countsPanelSongWarningsValue }
    public var fixtureScanCountsPanelMatchExport: Bool { fixtureDiagnostics.countsPanelMatchExport }
    public var invalidRootDiagnosticsExportPath: String { invalidRoot.exportPath }
    public var invalidRootExportContainsRootHealthBadge: Bool { invalidRoot.exportContainsBadge }
    public var invalidRootPanelRootHealthBadge: String { invalidRoot.panelBadge }
    public var invalidRootPanelBadgeMatchesExport: Bool { invalidRoot.panelBadgeMatchesExport }
    public var invalidRootPanelGlobalWarningLines: String { invalidRoot.panelGlobalWarningLines }
    public var invalidRootPanelGlobalWarningLinesMatchExport: Bool { invalidRoot.panelGlobalWarningLinesMatchExport }
    public var summaryTruncationDiagnosticsExportPath: String { summaryTruncation.exportPath }
    public var summaryTruncationDiagnosticsExportContainsTruncation: Bool { summaryTruncation.exportContainsTruncation }
    public var summaryTruncationPanelFootnote: String { summaryTruncation.panelFootnote }
    public var summaryTruncationPanelFootnoteMatchesDiagnostics: Bool { summaryTruncation.panelFootnoteMatchesDiagnostics }
    public var skippedSearchDiagnosticsExportPath: String { skippedSearch.exportPath }
    public var skippedSearchDiagnosticsExportContainsMatch: Bool { skippedSearch.exportContainsMatch }
    public var skippedSearchPanelQueryLine: String { skippedSearch.panel.queryLine }
    public var skippedSearchPanelQueryLineMatchesExport: Bool { skippedSearch.panel.queryLineMatchesExport }
    public var skippedSearchPanelMatchLines: String { skippedSearch.panel.matchLinesJoined }
    public var skippedSearchPanelMatchLinesMatchExport: Bool { skippedSearch.panel.matchLinesMatchExport }
}
